Repository jimasr/fit-ut, pull requests merged in 2023-03, with the labels that each got.

#2 Merge Home to Dev
  .DS_Store
  .gitignore
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/HomeActivity.java
  app/src/main/java/com/example/myapplication/MainActivity.java
  app/src/main/java/com/example/myapplication/fragment/HomeFragment.java
  app/src/main/res/drawable/bolt.png
  app/src/main/res/drawable/cardio.png
  app/src/main/res/drawable/default_icon.png
  app/src/main/res/drawable/home.png
  app/src/main/res/drawable/hour_icon.png
  app/src/main/res/drawable/progress_icon.png
  app/src/main/res/drawable/settings.png
  app/src/main/res/drawable/strength.png
  app/src/main/res/drawable/stretching.png
  app/src/main/res/drawable/strong_icon.png
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#3 Merge Workout to dev branch
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/WorkActivity.java
  app/src/main/java/com/example/myapplication/workout/WorkoutActivity.java
  app/src/main/java/com/example/myapplication/workout/WorkoutAdapter.java
  app/src/main/java/com/example/myapplication/workout/WorkoutHolder.java
  app/src/main/java/com/example/myapplication/workout/WorkoutItem.java
  app/src/main/res/layout/activity_work.xml
  app/src/main/res/layout/activity_workout.xml
  app/src/main/res/layout/workout_item.xml
Labels: enhancement

#5 fix: converting WorkoutActivity to WorkoutFragment
  app/src/main/java/com/example/myapplication/MainActivity.java
  app/src/main/java/com/example/myapplication/fragment/WorkoutFragment.java
  app/src/main/java/com/example/myapplication/util/WorkoutAdapter.java
  app/src/main/java/com/example/myapplication/util/WorkoutHolder.java
  app/src/main/java/com/example/myapplication/util/WorkoutItem.java
  app/src/main/java/com/example/myapplication/workout/WorkoutActivity.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_workout.xml
  app/src/main/res/layout/workout_item.xml
Labels: enhancement

#6 Merge Google-maps to Dev
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/entity/Place.java
  app/src/main/java/com/example/myapplication/fragment/HomeFragment.java
  app/src/main/java/com/example/myapplication/util/FetchData.java
  app/src/main/res/layout/fragment_home.xml
  build.gradle
Labels: enhancement, help wanted

#7 Merge Firebase
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/AuthActivity.java
  app/src/main/java/com/example/myapplication/MainActivity.java
  app/src/main/java/com/example/myapplication/fragment/HomeFragment.java
  app/src/main/java/com/example/myapplication/fragment/SignInFragment.java
  app/src/main/java/com/example/myapplication/fragment/SignUpFragment.java
  app/src/main/java/com/example/myapplication/util/FetchData.java
  app/src/main/res/drawable/login.jpg
  app/src/main/res/layout/activity_auth.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/layout/fragment_sign_up.xml
  build.gradle
Labels: enhancement

#9 Merge User to Dev
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/AuthActivity.java
  app/src/main/java/com/example/myapplication/fragment/HomeFragment.java
  app/src/main/java/com/example/myapplication/fragment/SettingsFragment.java
  app/src/main/java/com/example/myapplication/util/StorageManager.java
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_settings.xml
Labels: enhancement

#10 Add notification
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/MainActivity.java
  app/src/main/java/com/example/myapplication/service/WorkoutNotification.java
  app/src/main/res/values/strings.xml
Labels: enhancement

#14 Detail
  app/build.gradle
  app/src/main/java/com/example/myapplication/fragment/DetailFragment.java
  app/src/main/java/com/example/myapplication/fragment/ExerciseFragment.java
  app/src/main/res/drawable/rounded_corner.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_exercise.xml
  app/src/main/res/values/strings.xml
  settings.gradle
Labels: enhancement

#18 Detail design
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/fragment/DetailFragment.java
  app/src/main/java/com/example/myapplication/fragment/WorkoutFragment.java
  app/src/main/java/com/example/myapplication/util/ExerciseAdapter.java
  app/src/main/res/drawable-mdpi/cardio_removebg.png
  app/src/main/res/drawable-mdpi/chronometer.png
  app/src/main/res/drawable-mdpi/logo_color.png
  app/src/main/res/drawable-mdpi/logo_no_background.png
  app/src/main/res/drawable-mdpi/olympic_removebg.png
  app/src/main/res/drawable-mdpi/plyometrics_removebg.png
  app/src/main/res/drawable-mdpi/powerlifting_removebg.png
  app/src/main/res/drawable-mdpi/strength_removebg.png
  app/src/main/res/drawable-mdpi/stretching_removebg.png
  app/src/main/res/drawable-mdpi/strongman_removebg.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/exercise_item.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_exercise.xml
  app/src/main/res/layout/fragment_workout.xml
Labels: enhancement, question
